name: Publish Coosu.Storyboard
env:
  ProjectName: Coosu.Storyboard
on:
  create:
    tags:
      - "storyboard-v*.*.*"
  
jobs:
  build:
    name: Build and Release
    if: ${{ StartsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: |
        echo ${{ github.ref }}      
        dotnet publish Coosu.Storyboard --no-restore --no-self-contained --configuration Release --output ci-publish
        
    - name: action-minver
      uses: thefringeninja/action-minver@2.0.0-preview1
      id: version
      with:
        tag-prefix: storyboard-v
        minimum-major-minor: 1.0
        
    - name: Pack via 7z
      if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
      run: |
        mkdir -p ./ci-pack/
        7z a -mx9 -mfb=273 -ms -md=31 -myx=9 -mtm=- -mmt -mmtf -md=1536m -mmf=bt3 -mmc=10000 -mpb=0 -mlc=0 "./ci-pack/${{ env.ProjectName }}-v${{ steps.version.outputs.version }}.7z" "./ci-publish/*" -x!"${{ env.ProjectName }}" -r
      
    - name: Create a new GitHub release if a new tag is pushed
      uses: softprops/action-gh-release@v1
      if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        name: ${{ env.ProjectName }}-v${{ steps.version.outputs.version }}
        prerelease: true
        draft: false
        files: |
          ./ci-pack/${{ env.ProjectName }}-v${{ steps.version.outputs.version }}.7z
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: ${{ env.ProjectName }}/${{ env.ProjectName }}.csproj
        VERSION_STATIC: ${{ steps.version.outputs.version }}
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
